comment: false
coverage:
  round: up
  precision: 2
  range: 30..100
  status:
    patch: false
    project:
      default:
        informational: true
      application:
        informational: true
        paths: [packages/application]
      battery:
        informational: true
        paths: [packages/battery]
      brightness:
        informational: true
        paths: [packages/brightness]
      font:
        informational: true
        paths: [packages/font]
      permissions:
        informational: true
        paths: [packages/permissions]
      screen-orientation:
        informational: true
        paths: [packages/screen-orientation]
      sensors:
        informational: true
        paths: [packages/sensors]
      store-review:
        informational: true
        paths: [packages/store-review]
      web-browser:
        informational: true
        paths: [packages/web-browser]
