---
name: Packages CI
on:
  pull_request:
    paths:
      - '!example/**'
jobs:
  ci:
    name: Install, test and lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run lint
      - run: npm run test
